### ISSUE TITLE
Does remark-html work only from the command line?

### ISSUE THREAD

**Issue by kahwee** [remarkjs/remark-html#7]
I encounter an issue when trying to use only command line to execute `remark`. This is my `.remarkrc`

``` json
{
  "output": true,
  "plugins": {
    "lint": {
      "no-shell-dollars": false
    },
    "github": true,
    "comment-config": true,
    "toc": true,
    "validate-links": true,
    "html": true
  },
  "settings": {
    "commonmark": true,
    "bullet": "*"
  }
}
```

I then execute

``` sh
remark history.md --output history.html
```

This does not seem to work. Is `remark-html` intended to be used in conjunction with `.remarkrc` or do I have to do this programmatically.

Thanks.

**Comment by wooorm** [comment]
Please provide more information, such as version numbers, contents of files.

`remark-html` works with `.remarkrc` files on the CLI, and programatically on the API.

P.S. Read the [`docs/`](https://github.com/wooorm/remark/tree/master/doc)

**Comment by kahwee** [comment]
I upload my files to GitHub: https://github.com/kahwee/remark-test2

The exact error message is:

```
> remark testing.md --output testing.html

testing.md
        1:1  error    Error: Invalid value `true` for setting `options`
    at raise (/Users/kahwee/projects/remark-test2/node_modules/remark/lib/utilities.js:37:11)
    at Of.compilerPrototype.setOptions (/Users/kahwee/projects/remark-test2/node_modules/remark/lib/stringify.js:881:9)
    at Of.Compiler (/Users/kahwee/projects/remark-test2/node_modules/remark/lib/stringify.js:822:10)
    at new Of (/Users/kahwee/projects/remark-test2/node_modules/unherit/index.js:58:22)
    at Of.HTMLCompiler (/Users/kahwee/projects/remark-test2/node_modules/remark-html/index.js:57:26)
    at Processor.stringify (/Users/kahwee/projects/remark-test2/node_modules/unified/index.js:226:16)
    at Ware.stringify (/Users/kahwee/projects/remark-test2/node_modules/remark/lib/cli/file-pipeline/stringify.js:56:35)
    at Ware.<anonymous> (/Users/kahwee/projects/remark-test2/node_modules/wrap-fn/index.js:75:16)
    at Ware.<anonymous> (/Users/kahwee/projects/remark-test2/node_modules/wrap-fn/index.js:57:27)
    at next (/Users/kahwee/projects/remark-test2/node_modules/ware/lib/index.js:85:20)

✖ 1 error
```

To execute the test, run `npm run build`

Pardon me if I missed some details in `remark` docs. 

Thanks.

**Comment by wooorm** [comment]
Oh I see, don't use 'true' as the value for the keys in '.remarkrc', instead use 'null', in which case they default to an empty object!

**Comment by kahwee** [comment]
Hey thank you @wooorm, that explains.

Do you mind if I contact you through email? I want to improve Node.js guides generator based on https://github.com/nodejs/node/pull/4866

I want to know what your thoughts on how I should be implementing this where there is a template involved. Should I fork `remark-html` to do this?
